accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
  run-as: 65532

contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    - https://dl-cdn.alpinelinux.org/alpine/edge/testing
  packages:
    # "core"
    - alpine-base
    - ca-certificates-bundle

    # dev tools
    - bash
    - mysql-client
    - jq
    - step-cli
    - curl
    - grpc-cli
    - minio-client
    - cosign

entrypoint:
  command: /bin/bash -l

