contents:
  repositories:
    - https://dl-cdn.alpinelinux.org/alpine/edge/main
    - https://dl-cdn.alpinelinux.org/alpine/edge/community
    - https://dl-cdn.alpinelinux.org/alpine/edge/testing
  packages:
    # "core"
    - alpine-base
    - ca-certificates-bundle

    # dev tools
    - bash
    - mysql-client
    - jq
    - step-cli
    - curl
    - minio-client
    - cosign

entrypoint:
  command: /bin/bash -l

archs:
  - x86_64
  - aarch64
