name: PreSubmit-Build

on:
  pull_request:

jobs:
  build:
    name: Build OCI image
    runs-on: ubuntu-latest

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Generate snapshot date
      id: snapshot-date
      run: |
        echo ::set-output name=date::$(date -u +%Y%m%d)
      shell: bash

    - uses: chainguard-images/actions/apko-build@main
      with:
        tag: dev-toolbox:${{ steps.snapshot-date.outputs.date }}

    - uses: actions/upload-artifact@v3
      with:
        name: dev-toolbox.tar
        path: ./output.tar
